---
# build.yml

- name: Deploy Configs
  hosts: SNG_FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_skip_missing_devices: true
        cv_verify_certs: false
        cv_server: 10.18.172.131
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjczODE1ODEzMTE3NTgwNDEyODgsImRzbiI6IkFWRCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NDg4MjYyMjcsImlhdCI6MTcxODY3MjYzNCwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiZmQwMjA3YjYxMzQ2YzY4MDcxYjY2NjY3MDljY2Y2M2UzMTJmOTM2MjczNWEwYWIxM2Y1Njg0ZGQxYzY4ZWQ2My1EYld1VC1xbWdKSjJtUTFfUjlBNVJsYTBLQThLVjU2MXpuNl9mSDRuIn0.JWHMvyUfHfJYwjBot1w-c8SrctHd_bvttaHrg_UEAhtIHV2fdBDiSYHVi1oKGOtrUF3YkA90DRBihI8sxMqgnztYjSY1ryN7PZ9r7gcohBHcLRpIH4zWK0C6JNI8L0S57Pe8RI-HTL2Qw8ED06wuQ-mAcBUGodUBcy0C28nYA_guo62OjS-fSJT2R_Y1iTijgybDAqGu_82k5ZiJ0AbWsQ0rLBGr9QSarw3FE3azL4gD82AcKGmHAEF-L1mePvNz060CUJUIy7ESjKjMcV9jcwid2tMtCcvZ_XW-TS8wqaR2pjPmd3CYlcOcBehpZRb69o-nOdO2ZT8GXdo8zPfZisiV2bxZJdkDp67Um_E9DO9fZUF7vLcY1qo6OK4VoJNPzLFuXADJYzcrsckmYsTQurPJUEXP8TGQh-mVu6QGSPQ13wAZbbymLWv9usvhyAqOMXaq7c6vIEAhr7O0YhbYbDp7vWQ_fBgLJOoTRj5yFzoFI9mBdit_PzFMrbxhm1yrEswcAWqAhwVSdQmTOJQrHZly9XYEe3pA0eRQyAsBQxii6B1viZBda278l5GQx70_fUtfL138z-Upj1wIU60XViGGxozWyYp0Mr9nvNwapiW72eRV5WVuT4uLRPacv6QzpPFKFTfBR3uxKUYFoimYdBtjbXEorRCYmN0pOEa1JsU